### ISSUE TITLE
[4.0.0-alpha.1] Not working with ember-decorators

### ISSUE THREAD

**Issue by boris-petrov** [typed-ember/ember-cli-typescript#1166] opened 2020-06-25 15:03 UTC
Not sure if the problem is specifically with `ember-decorators` but it's one example where it doesn't work:

https://github.com/boris-petrov/ember-cli-typescript-bug

Most of the stuff is from blueprints, the only relevant part is the `foo-bar` component which has `@classNames('col-lg-2', 'col-md-4', 'col-sm-6', 'col-xs-12')`. These class names are not set on the `div`. If you remove the `hbs` file, it works fine, not sure why.

**Comment by chriskrycho** [comment] 2020-06-25 16:32
cc. @jamescdavis –

**Comment by dfreeman** [comment] 2020-06-25 17:02
This seems like it might be a bug in `ember-cli-babel` or `ember-cli-htmlbars`, as I see the same behavior even if I rename the component to `foo-bar.js` and remove `ember-cli-typescript` from the project's dependencies 🤔 

@rwjblue any idea where colocation + class decorators might be falling over?

**Comment by chriskrycho** [comment] 2020-06-25 17:11
I believe the problem is that colocation requires a named class to attach the template to, because under the hood it just does roughly this IIRC:

```js
// component.js
import Component, { setComponentTemplate } from '@ember/component';
import template from './component.hbs';

class MyComponent extends Component {}
setComponentTemplate(template, MyComponent);

export default MyComponent;
```

**Comment by chriskrycho** [comment] 2020-06-25 17:12
(Closing this as it's an upstream, but will link to the upstream issue once we have it filed.)

**Closed by chriskrycho** 2020-06-25 17:12 UTC
Labels: bug:other-package
