### ISSUE TITLE
`router.off` types missing

### ISSUE THREAD

**Issue by mydea** [typed-ember/ember-cli-typescript#1469] opened 2022-01-25 11:57 UTC
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [x] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__test-helpers
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] Other
  - [ ] I don't know

The types for `RouterService.off()` are missing. The ones for `RouterService.on()` are there, though.

**Comment by chriskrycho** [comment] 2022-01-25 16:49
Duplicate of #1161. If you can help out by opening a PR to Ember's docs to document it, we can get it in the types as well. Thanks!

**Closed by chriskrycho** 2022-01-25 16:49 UTC

**Comment by mydea** [comment] 2022-01-26 07:31
Damn, sorry, weird that this issue does not show up when searching for `router.off`, although it _is_ used in the other issues description :thinking: I'll try to get a docs PR in!
