### ISSUE TITLE
having typescript 3.8.3 as dependecy is throwing bugs 

### ISSUE THREAD

**Issue by TheLooseCannon** [typed-ember/ember-cli-typescript#1124] opened 2020-03-11 09:07 UTC
### `ember -v`
ember-cli: 3.16.0
node: 12.16.1
os: darwin x6

### `tsc -v`

  Version 3.8.3

### `ember-cli-typescript`
├─ @glimmer/component@1.0.0
│  └─ ember-cli-typescript@3.0.0
├─ ember-cli-typescript-blueprints@3.0.0
├─ ember-cli-typescript@3.1.3
└─ ember-load-initializers@2.1.1
   └─ ember-cli-typescript@2.0.2

### `tsconfig.json`

<details><summary><b>My tsconfig.json</b></summary><pre>
{
  "compilerOptions": {
    "target": "es2017",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "noFallthroughCasesInSwitch": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noEmitOnError": false,
    "noEmit": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "baseUrl": ".",
    "module": "es6",
    "experimentalDecorators": true,
    "paths": {
      "vegatrail/tests/*": [
        "tests/*"
      ],
      "vegatrail/*": [
        "app/*"
      ],
      "*": [
        "types/*"
      ]
    }
  },
  "include": [
    "app/**/*",
    "tests/**/*",
    "types/**/*"
  ]
}

  
</pre></details>

### What are instructions we can follow to reproduce the issue?
```sh
ember new sample; cd ./sample # Create a new ember app
ember install ember-cli-typescript # Set up typescript support
ember serve
```

### Now about that bug. What did you expect to see?
start the ember server

### What happened instead?

```
⠴ building... [Babel: @ember-data/model > applyPatches]/Users/username/Experiments/vegatrail/node_modules/typescript/lib/typescript.js:98681
                throw e;
                ^

```
this error was thrown

**Comment by devotox** [comment] 2020-03-11 11:15
@TheLooseCannon  https://github.com/typed-ember/ember-cli-typescript/issues/1103

**Comment by chriskrycho** [comment] 2020-03-11 16:54
Thanks for reporting; closing as duplicate of #1103!

**Closed by chriskrycho** 2020-03-11 16:54 UTC
