### ISSUE TITLE
Adding default value to field stops values from being passed in Handlebars invocations

### ISSUE THREAD

**Issue by tstormk** [typed-ember/ember-cli-typescript#468] opened 2018-12-10 09:09 UTC
### Which package(s) does this problem pertain to?
  - [ ] @types/ember
  - [ ] @types/ember__string
  - [ ] @types/ember__polyfills
  - [ ] @types/ember__object
  - [ ] @types/ember__utils
  - [ ] @types/ember__array
  - [ ] @types/ember__engine
  - [ ] @types/ember__debug
  - [ ] @types/ember__runloop
  - [ ] @types/ember__error
  - [ ] @types/ember__controller
  - [ ] @types/ember__component
  - [ ] @types/ember__routing
  - [ ] @types/ember__application
  - [ ] @types/ember__test
  - [ ] @types/ember__service
  - [ ] @types/ember-data
  - [ ] @types/rsvp
  - [ ] @types/ember-test-helpers
  - [ ] @types/ember-testing-helpers
  - [ ] Other
  - [X] I don't know

##### Reproduction Case
In a component that looks like the following:
```
import Component from '@ember/component';
// @ts-ignore: Ignore import of compiled template
import layout from './template';

export default class Test extends Component.extend({
  layout
}) {
  myField: boolean = false;
}
```

Template:
```
{{this.myField}}
```

Invoking the component by doing `<TestTest @myField={{true}} />` will have the component printing `false`. Now, if I remove the default value from the field so it looks like `myField?: boolean`, the component will print `true` as it's supposed to.

The same goes for fields of other types.

### Now about that bug. What did you expect to see?
I expected the value passed in the component invocation to be displayed instead of the default field value.

### What happened instead?
Adding a default value to a field makes the component always use that value instead of any value passed to it.

**Comment by chriskrycho** [comment] 2018-12-10 19:09
This is not a bug, actually! It's a function of how class properties work – see [this blog post](https://www.chriskrycho.com/2018/ember-ts-class-properties.html) and [this discussion in Ember Decorators](https://ember-decorators.github.io/ember-decorators/docs/class-fields) for details. However, it *will* be resolved by Ember 3.6, and you can use [this polyfill](https://www.npmjs.com/package/ember-native-class-polyfill) to get it in earlier versions!

**Closed by chriskrycho** 2018-12-10 19:09 UTC
