### ISSUE TITLE
ts:precompile fails with no useful error

### ISSUE THREAD

**Issue by BryanCrotaz** [typed-ember/ember-cli-typescript#943] opened 2019-11-11 01:13 UTC
Run `ember ts:precompile` on the github repo `silver-curve/ember-debug-logger#fix-typescript-types`

The following error occurs:

```
=================================================================================

ENV Summary:

  TIME: Mon Nov 11 2019 01:09:12 GMT+0000 (Greenwich Mean Time)
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /usr/local/bin/ember
  - ts:precompile
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/24/9c9x7j316gbd3z5wg84fghqc0000gn/T
  SHELL: /bin/bash
  PATH:
  - /Library/Frameworks/Python.framework/Versions/3.7/bin
  - /Users/bryan/.yarn/bin
  - /Users/bryan/.config/yarn/global/node_modules/.bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/share/dotnet
  - ~/.dotnet/tools
  - /Library/Frameworks/Mono.framework/Versions/Current/Commands
  - /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
  PLATFORM: darwin x64
  FREEMEM: 242495488
  TOTALMEM: 17179869184
  UPTIME: 1472238
  LOADAVG: 2.4169921875,3.68212890625,4.89306640625
  CPUS:
  - Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz - 3000
  - Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz - 3000
  - Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz - 3000
  - Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz - 3000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - cldr: 33.1
  - http_parser: 2.8.0
  - icu: 62.1
  - modules: 64
  - napi: 3
  - nghttp2: 1.34.0
  - node: 10.15.0
  - openssl: 1.1.0j
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.23.2
  - v8: 6.8.275.32-node.45
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Command failed with exit code 2: tsc --allowJs false --noEmit false --rootDir /Users/bryan/Projects/ember-debug-logger --isolatedModules false --declaration --declarationDir /var/folders/24/9c9x7j316gbd3z5wg84fghqc0000gn/T/e-c-ts-precompile-52385 --emitDeclarationOnly
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Command failed with exit code 2: tsc --allowJs false --noEmit false --rootDir /Users/bryan/Projects/ember-debug-logger --isolatedModules false --declaration --declarationDir /var/folders/24/9c9x7j316gbd3z5wg84fghqc0000gn/T/e-c-ts-precompile-52385 --emitDeclarationOnly
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Command failed with exit code 2: tsc --allowJs false --noEmit false --rootDir /Users/bryan/Projects/ember-debug-logger --isolatedModules false --declaration --declarationDir /var/folders/24/9c9x7j316gbd3z5wg84fghqc0000gn/T/e-c-ts-precompile-52385 --emitDeclarationOnly
    at makeError (/Users/bryan/Projects/ember-debug-logger/node_modules/ember-cli-typescript/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/Users/bryan/Projects/ember-debug-logger/node_modules/ember-cli-typescript/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

=================================================================================
```

**Comment by BryanCrotaz** [comment] 2019-11-11 01:30
duplicate of #917

running `tsc` shows the real error

**Comment by chriskrycho** [comment] 2019-11-21 17:05
Thanks for reporting this and sorry for the delayed response. I'm closing this as a duplicate of #917 – and thanks for catching that! One of us will try to see if we can get it sorted sometime soon-ish. If you happen to have time and end up figuring out why it's not getting piped through into the Ember build output, please let us know!

**Closed by chriskrycho** 2019-11-21 17:05 UTC
