### ISSUE TITLE
Ember Serve crashes on Typechecking failed

### ISSUE THREAD

**Issue by lbrande** [typed-ember/ember-cli-typescript#1477] opened 2022-02-09 00:02 UTC
Currently ember serve crashes if typechecking fails. This is very annoying as it means you have to restart it all the time.

**Comment by chriskrycho** [comment] 2022-02-10 14:48
Duplicate of #1439. TL;DR: it needs a fix upstream in Ember CLI! Thanks for reporting.

**Closed by chriskrycho** 2022-02-10 14:48 UTC

**Comment by chriskrycho** [comment] 2022-02-10 22:30
@lbrande no, that's just a workaround for the upstream issue. If you look at the lines immediately above the one you linked, you'll see that the code *explicitly says* that it will already have printed the errors for the CLI side:

https://github.com/typed-ember/ember-cli-typescript/blob/952ec833b2b2a2f8c1d770019780dd12f387a76d/ts/addon.ts#L80-L81

This thrown error is how we inject type errors into the build in a way that can trigger a type error *page*, i.e. the browser view of it (not just the CLI view of it).

**Comment by krisselden** [comment] 2022-02-28 20:43
@chriskrycho you could the default to not fail on typecheck when using --serve or building dev and test.

**Comment by chriskrycho** [comment] 2022-03-01 03:24
@krisselden yeah, we discussed that option over on #1439. The difference is that Ember CLI has “throw an error” as a part of its *design*: that’s how you can inject errors into the pipeline which end up rendered to the HTML page Ember shows for errors in the build pipeline, which has long been a feature Ember TS devs really like.

**Comment by jdaviderb** [comment] 2022-08-11 15:06
Hey guys, I added this on ember-cli-builds.js and now it works
ref: https://github.com/ember-cli/ember-cli/issues/9404#issuecomment-785703073
```
process.on("uncaughtException", function (err) {
  console.log("Typescript error");
  console.error(err.stack);
});
```
