### ISSUE TITLE
error TS2554: Expected 0-1 arguments, but got 2.

### ISSUE THREAD

**Issue by danielgratzl** [typed-ember/ember-cli-typescript#86] opened 2017-12-05 17:19 UTC
When using Mixins in the extend method of a component I get the following errors

```
error TS2554: Expected 0-1 arguments, but got 2.
```

./app/mixins/foo.ts
```
import Ember from 'ember';

const { Mixin, computed } = Ember;

export default Mixin.create({
  foo: 'foo'
});

```

./app/components/bar.ts
```
import Ember from 'ember';
import FooMixin from '../mixins/foo';

const { Component } = Ember;

export default Component.extend(FooMixin, {
  bar: 'bar'
});

```

**Comment by dwickern** [comment] 2017-12-05 17:26
Are you using the latest typings from `@types/ember`?

**Comment by danielgratzl** [comment] 2017-12-06 07:32
Yes, I used the setup described in the README.md and my package.json shows  
```
"@types/ember": "^2.8.2",
"@types/ember-testing-helpers": "0.0.3",
"@types/rsvp": "^4.0.0",
"ember-cli-typescript": "^1.0.5",
"jquery": ">= 1.7.0 < 4.0.0",
"typescript": "^2.6.2",
```

**Comment by chriskrycho** [comment] 2017-12-06 12:42
Huh. I have a fair number of mixing applied this way, but I think they’re all in controllers and routes, so I’ll test locally and see if I can reproduce e sometime today.

**Comment by danielgratzl** [comment] 2017-12-14 08:08
@chriskrycho Have you been able to reproduce the behaviour?

**Comment by chriskrycho** [comment] 2017-12-15 03:02
Apologies, but no: had another issue come up at work. I should be able to dig in either tomorrow or Monday, though.

**Comment by chriskrycho** [comment] 2017-12-16 20:03
@danielgratzl so I just built this out myself and… I can't reproduce. 😬 

A suggestion which *may* fix it:

- Change all the `@types/` values for the Ember-related types in your package.json to `"*"` instead of a specific version
- Do `yarn upgrade @types/ember @types/rsvp @types/ember-testing-helpers` (or equivalent `npm` invocation)
    * for good measure, after doing so you might also `rm -rf node_modules` and then `yarn` or `npm install` again

Then let me know what you see. 🤔

**Comment by chriskrycho** [comment] 2018-01-25 00:08
@danielgratzl can you confirm this is still a problem for you after trying the above? If not, I'll close this issue; trying to keep issue count meaningful.

**Comment by chriskrycho** [comment] 2018-02-10 03:39
I’m closing this as I can’t reproduce it and haven’t gotten any further info on how to do so. Please feel free to reopen if there’s more info to share!

**Closed by chriskrycho** 2018-02-10 03:39 UTC
