### ISSUE TITLE
Can't use module from npm

### ISSUE THREAD

**Issue by BryanCrotaz** [typed-ember/ember-cli-typescript#78] opened 2017-10-16 09:51 UTC
```
ember addon my-addon
cd my-addon
ember install ember-cli-typescript
ember install ember-browserify
npm install ts-mockito
```
In `my-test.ts`
```
import mockito from 'npm:ts-mockito';
const {mock} = mockito;
```
In test run:
```
Died on test #1     at TestLoader.moduleLoadFailure (http://localhost:4200/assets/test-support.js:7866:24)
    at TestLoader.<anonymous> (http://localhost:4200/assets/test-support.js:8094:16)
    at TestLoader.require (http://localhost:4200/assets/test-support.js:8082:27)
    at TestLoader.loadModules (http://localhost:4200/assets/test-support.js:8074:16)
    at loadTests (http://localhost:4200/assets/test-support.js:7919:22)
    at start (http://localhost:4200/assets/test-support.js:7954:7)
    at Module.callback (http://localhost:4200/assets/my-test.js:108:28): Could not find module `ts-mockito` imported from `dummy/tests/unit/utils/my-test`
```

**Comment by chriskrycho** [comment] 2017-10-18 23:47
(Duplicate of #8.)

Note that this isn’t a bug in ember-cli-typescript: it’s a function of the fact that TypeScript goes looking for a moduile named `npm:ts-mockito` to try to resolve these imports, doesn’t find one, and accordingly doesn’t succeed at resolving the import.

You can work around this by creating a TypeScript shim module named `npm:ts-mockito` which simply imports and re-exports the `ts-mockito` exports. Something like this *should* work (I haven’t tested it, though!):

```ts
declare module 'npm:ts-mockito' {
  import mockito from 'ts-mockito';
  export default mockito;
}
```

**Closed by chriskrycho** 2017-10-18 23:47 UTC
