### ISSUE TITLE
ember-concurrency-decorators typehinting.

### ISSUE THREAD

**Issue by pjcarly** [typed-ember/ember-cli-typescript#634] opened 2019-03-25 14:01 UTC
ember-concurrency-decorators lacks proper typehinting in the IDE. 

![image](https://user-images.githubusercontent.com/2808694/54925042-d0565a00-4f0d-11e9-909b-0fd463a47c06.png)

The limitations are clear. Perhaps there can be a solution in the future.
At the least we could document this behavior.

**Comment by chriskrycho** [comment] 2019-03-25 14:25
Elaboration: this happens when you write a decorated task like this:

```ts
import Component from '@ember/component';
import { action } from '@ember-decorators/object';
import { task } from 'ember-concurrency-decorators';

export default class MyComponent extends Component {
  @task
  *fetchRecords() {
    // whatever behavior
  }

  @action
  doSomething() {
    this.fetchRecords.perform();
  }
```

The problem is that the type of `*fetchRecords` from TS' perspective is a generator function; decorators are not currently allowed to change the type of the thing they decorate. But this decorator is in fact *wrapping* the generator function in a `Task` type which has a `perform` method, so the type as TS sees it and the type as it behaves at runtime are different.

**Comment by buschtoens** [comment] 2019-03-29 09:48
Related to https://github.com/machty/ember-concurrency-decorators/issues/41

**Comment by chriskrycho** [comment] 2023-09-28 22:43
This was resolved via a series of workarounds (hacks? But of a respectable variety!) in ember-concurrency. Thanks for the original reports, folks!

**Closed by chriskrycho** 2023-09-28 22:43 UTC
Labels: docs
