### ISSUE TITLE
Service example needs clarification?

### ISSUE THREAD

**Issue by tabeth** [typed-ember/ember-cli-typescript#119] opened 2018-02-15 16:24 UTC
Hello! 

Was wanting some clarity on the service injection example in `README.md`. 

If you do the following:

```typescript
// my-app/services/session.ts
import Service from '@ember/service';
import RSVP from 'rsvp';

export default class Session extends Service {
  login(email: string, password: string): RSVP.Promise<string> {
    // login and return the confirmation message
  }
}

declare module '@ember/service' {
  interface Registry {
    session: Session;
  }
}
```

```typescript
// my-app/components/user-profile.ts
import Component from '@ember/component';
import { inject as service } from '@ember/service';

export default class UserProfile extends Component {
  session = service('session');
  init(this: UserProfile) {
    this._super(...arguments);
    this.get('session'); /* Undefined */
  }
}
```

---

As you can see, `session` is undefined in `init`, and most other places I've tried. I haven't tried it for `actions`, so maybe that's a unique case. In any case, the documentation currently makes it sound like following the example as shown above will make it work in a regular Ember fashion, but from my brief testing it looks like you actually need to do something like below to make it work.

```typescript
// my-app/components/user-profile.ts
import Component from '@ember/component';
import { inject as service } from '@ember/service';

export default class UserProfile extends Component.extend({
  session: service('session');
}) {
  init(this: UserProfile) {
    this._super(...arguments);
    this.get('session'); /* Defined */
  }
}
```

Is this behavior by design, or is this a bug?

**Comment by chriskrycho** [comment] 2018-02-15 21:11
Thanks for the bug report, @tabeth!

I'm seeing it resolve in exactly the way you have in your first example in my app, though there are some *other* (previously undiscovered) issues with the registry as we have it. Can you put together a gist with a minimal reproduction so we can push on it a bit?

**Comment by tabeth** [comment] 2018-02-16 15:59
It's my pleasure @chriskrycho.

I created a brand new ember project and was not able to replicate the issue even though my project originally demonstrated the problem. Upon deleting `node_modules` and downloading the dependencies I was no longer to replicate the issue on my own project. For now I'll just chalk to this up to a stale build or some other shenanigans. If the problem crops up again I'll replicate it in a new repository and re-open the issue with a demonstration.

**Comment by chriskrycho** [comment] 2018-02-16 16:10
Thank you!

**Comment by tabeth** [comment] 2018-02-16 16:18
It seems just as soon as I typed that I was able to replicate the issue. I had nearly forgotten that the issue does not occur during Javascript <-> Typescript compilation, but actually during runtime. 

Take a [look at the repository](https://github.com/tabeth/ember-cli-typescript--service-example). I've created that demonstrates the issue. Particularly, take look at the [controller](https://github.com/tabeth/ember-cli-typescript--service-example/blob/master/app/controllers/application.ts) I've created. Both services used in the example are the same, other than their name. The main difference is where they are as pointed out earlier.

Let me know if anything looks off!

**Comment by chriskrycho** [comment] 2018-02-16 17:12
@tabeth I think this is probably a function of the (admittedly surprising to lots of Ember users!) difference between *property initialization* and *prototype extension* – where the latter is what's happening on `.extend` and the former is what's happening in the body of a class definition. If you look at [this Ember Twiddle](https://ember-twiddle.com/8b6d00f8572f86439f636f8d4274ddf8?openFiles=controllers.application.js%2C), you can see two things at play:

- the ordering of when the `init` methods run and when the `constructor` runs (perhaps surprisingly, and importantly for this, `constructor` runs last)
- the actual behavior of injection using `session = service('session')` relative to those.

Basically, if you're using property initialization, you'll need to make sure you're doing things _after_ the constructor runs, because that's what property initialization is equivalent to and compiles to: just assigning those directly directly in the constructor.

This confusion will *largely* go away in a world where we're using decorators, as they'll be back to installing these properties on the prototype (if I'm understanding correctly what @pzuraq intends).

Sorry about the confusion here. When I (probably sometime after EmberConf next month) get around to reorganizing the material in the README into actual guides, I'll note this.

Closing this as it's not a bug, but feel free to keep discussing here!

**Closed by chriskrycho** 2018-02-16 17:12 UTC

**Comment by tabeth** [comment] 2018-02-16 17:26
Ah, I see. Thanks for the explanation!
